name: posture_app
description: Flutter app prototype with posture coaching data models and authentication flow.
version: 0.1.0
publish_to: "none"
environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.1
  meta: ^1.16.0
  video_player: ^2.9.5
  smooth_page_indicator: ^1.1.0
  haptic_feedback: '^0.5.1+1'
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  shimmer: ^3.0.0
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
