// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMPsy7n-GbOZO6pjU6ZUU-tq26Hhriw7k',
    appId: '1:465049224153:web:bf51437cdd7487a5aa4fc8',
    messagingSenderId: '465049224153',
    projectId: 'baumann-app',
    authDomain: 'baumann-app.firebaseapp.com',
    storageBucket: 'baumann-app.firebasestorage.app',
    measurementId: 'G-7HC6PGDFZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIwFPXSSJCddSn1VgdWlxFL4-SCJD_8uE',
    appId: '1:465049224153:android:6786ff9443355ef4aa4fc8',
    messagingSenderId: '465049224153',
    projectId: 'baumann-app',
    storageBucket: 'baumann-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB73yUfgqJUyAdNcnh5Ff1ccDoRGmfEikA',
    appId: '1:465049224153:ios:d3bd53e4fd1c6b4caa4fc8',
    messagingSenderId: '465049224153',
    projectId: 'baumann-app',
    storageBucket: 'baumann-app.firebasestorage.app',
    iosBundleId: 'com.Istituto-Baumann.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB73yUfgqJUyAdNcnh5Ff1ccDoRGmfEikA',
    appId: '1:465049224153:ios:d3bd53e4fd1c6b4caa4fc8',
    messagingSenderId: '465049224153',
    projectId: 'baumann-app',
    storageBucket: 'baumann-app.firebasestorage.app',
    iosBundleId: 'com.Istituto-Baumann.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMPsy7n-GbOZO6pjU6ZUU-tq26Hhriw7k',
    appId: '1:465049224153:web:584c82349bb4e0d9aa4fc8',
    messagingSenderId: '465049224153',
    projectId: 'baumann-app',
    authDomain: 'baumann-app.firebaseapp.com',
    storageBucket: 'baumann-app.firebasestorage.app',
    measurementId: 'G-5TDNY65FZK',
  );

}